[package]
name = "runix-inject"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"] # TODO should be cdylib, see https://github.com/geofft/redhook/issues/8

[dependencies]
redhook = "2.0"
libc = "0.2"
lazy_static = "1"
