[package]
name = "runix-build"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1"
itertools = "0.10"

# This should be a dev dependency, but that needs
# fetlock support
serial_test = "0.9.0"
