name: "Build and test"
on:
  pull_request:
  push:
   - main
   - ci-test
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=./nix/pkgs.nix

    - uses: cachix/cachix-action@v10
      with:
        name: runix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix-build
    - name: "Run tests"
      run: |
        nix-shell --attr ci nix/shell.nix --run '
          set -eux
          "$RUNIX_TEST_EXE" --include-ignored
        '
    - name: "Cross-compile"
      run: |
        nix-shell --attr ci nix/shell.nix --run '
          set -eux
          gup -u build/platforms/all/bootstrap
        '
