name: "Build and test"
'on':
  pull_request:
  push:
    branches:
    - main
    - ci-test
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-22.05

    - uses: cachix/cachix-action@v10
      with:
        name: runix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - run: nix-build
    - run: nix-build --argstr platform Darwin-aarch64
    # - run: nix-build --argstr platform Linux-x86_64

      # TODO make this `all` platforms when Linux builds in CI
    - name: "Create bootstrap artifacts"
      run: |
        nix-shell --attr ci nix/shell.nix --run '
          set -eux
          gup -u build/platforms/{Darwin-x86_64,Darwin-aarch64}/bootstrap.dir
          set +x
        '
    - name: "Log platform sizes"
      run: |
        du -hs build/platforms/*/bootstrap.dir/store | while read line; do
          echo "::notice::$line"
        done

    - name: "Run tests"
      run: |
        nix-shell --attr ci nix/shell.nix --run 'gup test'
