name: "Build and test"
'on':
  pull_request:
  push:
    branches:
    - main
    - ci-test
jobs:
  ci:
    runs-on: macos-latest
    env:
      USE_SYSTEM_CACHIX: "1"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v20
      with:
        nix_path: nixpkgs=channel:nixos-22.05
        extra_nix_config: |
          max-jobs = 6

    - uses: cachix/cachix-action@v12
      with:
        name: runix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Basic tests"
      run: |
        nix-shell --attr ci nix/shell.nix --run './test.sh'

    - name: "Build all platforms"
      run: nix-build --no-out-link nix/all-platforms.nix

    - name: "Integration tests"
      env:
        TEST_FLAGS: "--ignored"
      run: |
        nix-shell --attr ci nix/shell.nix --run './test.sh --ignored --skip docker'

    - name: "Create bootstrap artifacts"
      run: |
        nix-shell --attr ci nix/shell.nix --run '
          set -eux
          gup -j6 -u build/platforms/all/bootstrap.dir
          set +x
        '
    - name: "Log platform sizes"
      run: |
        du -hs build/platforms/*/bootstrap.dir/store | while read line; do
          echo "::notice::$line"
        done
