name: "Build and test"
'on':
  pull_request:
  push:
    branches:
    - main
    - ci-test
jobs:
  tests:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixos-22.05

    - uses: cachix/cachix-action@v10
      with:
        name: runix
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: "Build"
      run: nix-build

    - name: "Run tests"
      run: |
        nix-shell --attr ci nix/shell.nix --run '
          set -eux
          "$RUNIX_TEST_EXE" --include-ignored
        '

    - name: "Build all platforms"
      run: |
        nix-shell --attr ci nix/shell.nix --run '
          set -eux
          gup -u build/platforms/all/bootstrap
        '
